# Generated by Django 2.2.12 on 2022-01-15 19:23

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_group', to='otree.Session')),
            ],
            options={
                'db_table': 'general_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'general_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('audio', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Enter the word in lowercase')),
                ('Q1', otree.db.models.IntegerField(choices=[[1, 'Yes'], [2, 'No']], null=True, verbose_name='Will you play with the same group members in every round?')),
                ('Q2', otree.db.models.IntegerField(choices=[[1, '45 secs'], [2, '90 secs'], [3, 'randomly between the range of 45-90 seconds']], null=True, verbose_name='How much time do you have to decide?')),
                ('Q3', otree.db.models.IntegerField(choices=[[1, '100M'], [2, '300M'], [3, '900M'], [4, 'NOTA']], null=True, verbose_name='Suppose in a round, you do not invest but someone else invests from your group. How much do you earn?')),
                ('Q4', otree.db.models.IntegerField(choices=[[1, '100M'], [2, '300M'], [3, '900M'], [4, 'NOTA']], null=True, verbose_name='Suppose in a round, you invest before anyone else in the group. How much do you earn?')),
                ('Q5', otree.db.models.IntegerField(choices=[[1, '100M'], [2, '300M'], [3, '900M'], [4, 'NOTA']], null=True, verbose_name='Suppose in a round, no one from your group invests. How much do you earn?')),
                ('Q6', otree.db.models.IntegerField(choices=[[1, 'All'], [2, 'random from 1-10 & 11'], [3, 'Last'], [4, 'First']], null=True, verbose_name='Which round will you be paid for?')),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='Please enter your age')),
                ('gender', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10000, null=True, verbose_name='Please select your gender')),
                ('name', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please select a name from the list given below')),
                ('first_name', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please enter your First Name')),
                ('last_name', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please Enter your Last Name')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Subsession')),
            ],
            options={
                'db_table': 'general_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Subsession'),
        ),
    ]
