# Generated by Django 2.2.12 on 2022-01-15 19:23

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javatest_group', to='otree.Session')),
            ],
            options={
                'db_table': 'javatest_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='javatest_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'javatest_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('randCode', otree.db.models.IntegerField(null=True)),
                ('javaTest', otree.db.models.IntegerField(null=True)),
                ('javaAnswer', otree.db.models.IntegerField(null=True)),
                ('ping', otree.db.models.IntegerField(null=True, verbose_name='Ping:')),
                ('download', otree.db.models.FloatField(null=True, verbose_name='Download Speed:')),
                ('upload', otree.db.models.FloatField(null=True, verbose_name='Upload Speed')),
                ('pledge1', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Be available for the full time of the experiment')),
                ('pledge2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Devote my full attention to the experiment and not engage in other activities, such as browsing the internet')),
                ('pledge3', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Put my mobile devices in silent mode and not use them during the experiment')),
                ('pledge4', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Not communicate with any other participants during the session')),
                ('pledge5', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='I checked my internet speed and have a ping speed under 100')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='javatest.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javatest_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javatest_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='javatest.Subsession')),
            ],
            options={
                'db_table': 'javatest_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='javatest.Subsession'),
        ),
    ]
