# Generated by Django 2.2.12 on 2022-01-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('javatest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pledge5',
        ),
    ]
